### ISSUE TITLE
whereRoleIn function

### ISSUE THREAD

**Issue by eraporsmk** [santigarcor/laratrust#397] opened 2020-04-23 19:52 UTC
- Laravel Version: 7.7.1 
- Laratrust Version: 5.2.*

### Description:
Request whereRoleIn function like ```User::whereRoleIn(['admin', 'superadmin'])->get();```

### Steps To Reproduce:
Improve
```
public function scopeWhereRoleIs($query, $role = '', $team = null, $boolean = 'and')
    {
        $method = $boolean == 'and' ? 'whereHas' : 'orWhereHas';

        return $query->$method('roles', function ($roleQuery) use ($role, $team) {
            $teamsStrictCheck = Config::get('laratrust.teams_strict_check');
            if(is_array($role)){
                $roleQuery->whereIn('name', $role)
                ->when($team || $teamsStrictCheck, function ($query) use ($team) {
                    $team = Helper::getIdFor($team, 'team');
                    return $query->where(Helper::teamForeignKey(), $team);
                });
            } else {
            $roleQuery->where('name', $role)
                ->when($team || $teamsStrictCheck, function ($query) use ($team) {
                    $team = Helper::getIdFor($team, 'team');
                    return $query->where(Helper::teamForeignKey(), $team);
                });
            }
        });
    }
```

**Comment by santigarcor** [comment] 2020-04-24 13:27
Duplicate of #395

**Closed by santigarcor** 2020-04-24 13:27 UTC
Labels: duplicate
