### ISSUE TITLE
Call to undefined method Illuminate\Events\Dispatcher::fire()

### ISSUE THREAD

**Issue by harshadvala** [santigarcor/laratrust#341] opened 2019-04-09 05:30 UTC
Call to undefined method Illuminate\Events\Dispatcher::fire()

vendor\santigarcor\laratrust\src\Traits\LaratrustHasEvents.php"
line: 46

I facing this error with laravel 5.8

**Comment by santigarcor** [comment] 2019-04-10 16:09
Duplicate of #340

**Closed by santigarcor** 2019-04-10 16:09 UTC
